version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-server:
    build: ewm-stats-service/stats-server
    container_name: stats-server
    image: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - STATS_DB_URL=jdbc:postgresql://stats-db:5432/stats-db
      - STATS_DB_USER=test
      - STATS_DB_PASSWORD=test

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "5431:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ewm-main-service
    container_name: ewm-main-service
    image: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - main-db
    environment:
      - CLIENT_PORT=8080
      - STATS_SERVER_URL=http://stats-server:9090
      - MAIN_DB_URL=jdbc:postgresql://main-db:5431/main-db
      - MAIN_DB_USER=test
      - MAIN_DB_PASSWORD=test