version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-server:
    build: ewm-stats-service/stats-server
    container_name: stats-server
    image: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - DB_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-client:
    build: ewm-stats-service/stats-client
    container_name: stats-client
    image: stats-client
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - CLIENT_PORT=8080
      - STATS_SERVER_URL=http://stats-server:9090